### ISSUE TITLE
dialog反射数据获取错误

### ISSUE THREAD

**Issue by Mcayear** [MemoriesOfTime/MemoriesOfTime-GameCore#48]
### ❔怎么发生
当通过dialog的按钮打开假箱子ui时，发生报错。

### 报错信息
```
2022-11-07 08:48:56.188 [main] ERROR - [MemoriesOfTime-GameCore]: 反射获取数据时出现错误！
java.lang.NoSuchFieldException: DATA_URL_TAG
	at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
	at cn.lanink.gamecore.utils.EntityUtils.getEntityField(EntityUtils.java:27) ~[MemoriesOfTime-GameCore-1.6.3.jar:?]
	at cn.lanink.gamecore.form.windows.AdvancedFormWindowDialog.send(AdvancedFormWindowDialog.java:146) ~[MemoriesOfTime-GameCore-1.6.3.jar:?]
	at com.smallaswater.npc.dialog.DialogPages$DialogPage.send(DialogPages.java:127) ~[RsNPC-2.2.2-SNAPSHOT.jar:?]
	at com.smallaswater.npc.dialog.DialogPages$DialogPage.lambda$null$1(DialogPages.java:108) ~[RsNPC-2.2.2-SNAPSHOT.jar:?]
	at cn.lanink.gamecore.form.element.ResponseElementDialogButton.callClicked(ResponseElementDialogButton.java:29) [MemoriesOfTime-GameCore-1.6.3.jar:?]
	at cn.lanink.gamecore.form.windows.AdvancedFormWindowDialog.onEvent(AdvancedFormWindowDialog.java:182) [MemoriesOfTime-GameCore-1.6.3.jar:?]
	at cn.lanink.gamecore.form.WindowListener.onDataPacketReceive(WindowListener.java:40) [MemoriesOfTime-GameCore-1.6.3.jar:?]
	at cn.nukkit.plugin.PNXMethodEventExecutor$8.execute(EventHandler@cn.lanink.gamecore.form.WindowListener#onDataPacketReceive) [?:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:61) [PowerNukkitX.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:582) [PowerNukkitX.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:2611) [PowerNukkitX.jar:?]
	at com.blocklynukkit.loader.other.ProxyPlayer.handleDataPacket(ProxyPlayer.java:268) [BlocklyNukkit-12915-beta-r16-j17.jar:?]
	at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:154) [PowerNukkitX.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:94) [PowerNukkitX.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:227) [PowerNukkitX.jar:?]
	at cn.nukkit.Server.tick(Server.java:1500) [PowerNukkitX.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1279) [PowerNukkitX.jar:?]
	at cn.nukkit.Server.start(Server.java:1239) [PowerNukkitX.jar:?]
	at cn.nukkit.Server.<init>(Server.java:894) [PowerNukkitX.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:160) [PowerNukkitX.jar:?]
```

**Comment by lt-name** [comment]
使用了错误的gamecore分支
